version: '3'
services:
  database:
    image: postgres
    container_name: postgres-tinnova
    environment:
      - POSTGRES_DB=tinnova
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432      